enable:
  MFC: true
  CB: true
  Pixiv: true
  Twitch: true
  Mixer: true
  Youtube: true
  FC2: true
  daemon: false
recording:
  autoConvertType: mp4
  captureDirectory: capturing
  completeDirectory: captured
  postprocess: "scripts/postprocess_ffmpeg.sh"
  dateFormat: YYYYMMDD_HHmmss
  includeSiteInFile: false
  includeSiteInDir: false
  streamerSubdir: true
  siteSubdir: true
  keepTsFile: false
  minSize: 0
  maxSize: 0
postprocess: ""
log:
  enable: true
  append: true
tui:
  enable: false
  logshown: true
  listshown: true
  allowUnicode: false
colors:
  name: magenta
  state: yellow
  offline: blue
  prompt: blue
  file: green
  time: grey
  site: green
  cmd: grey
  debug: yellow
  error: red
proxy:
  enable: false
  server: socks5://127.0.0.1:1080
debug:
  log: false
  recorder: false
  errortrace: false
