name: YOUTUBE
plugin: ./lib/plugins/basic
siteUrl: https://www.youtube.com/channel/
urlback: ""
enable: true
m3u8fetch: scripts/m3u8_youtubedl.sh
m3u8fetch_args: []
recorder: scripts/record_ffmpeg.sh
recorder_args: []
scanInterval: 300
batchSize: 5
streamers: []
